project:
  type: book
  output-dir: _book
    
book:
  title: "Product Management"
  favicon: images/favicon-fullstack.svg
  author: "Scott Murff"
  date: "1/9/2026"
  chapters:
    - part: Syllabus
      chapters:
        - index.qmd
        - 00-schedule.qmd
        - 00-assessments.qmd
        - 00-release-notes.qmd
    - part: Foundations
      chapters:
        - 01-pm-ai-era.qmd
    - part: Aim
      chapters:
        - product-strategy.qmd
        - product-morality.qmd
        - 02-problems-worth-solving.qmd
    - part: Discover
      chapters:
        - 03-problem-discovery.qmd
        - 04-validating-opportunities.qmd
    - part: Build
      chapters:
        - 05-building-your-mvp.qmd
        - 07-platform-strategy.qmd
        - 06-testing-with-users.qmd
        - 11-sustainable-code.qmd
    - part: Grow
      chapters:
        - 08-measuring-what-matters.qmd
        - 09-go-to-market.qmd
        - 10-business-models.qmd
        - 12-final-presentations.qmd
    - part: References
      chapters:
        - 93-why-this-class-works.qmd
        - 94-problem-discovery-framework.qmd
        - 95-eng-checklist.qmd
        - 96-code-base-review.qmd
        - 97-resources.qmd
        - 97-thought-leaders.qmd
        - 97-canon.qmd
        - 98-tools.qmd
        - 99-prompts.qmd
        - 99-works-cited.qmd

bibliography: references.bib
csl: informs.csl

format:
  html:
    include-in-header: _header.html
    include-after-body: _footer.html
    theme: cosmo
    #link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    toc: true
    number-sections: false
execute:
  eval: false
    
toc-title: On this page
